//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hemsida.Data.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public System.Guid GameId { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> AwayScore { get; set; }
        public Nullable<System.Guid> HomeTeam { get; set; }
        public Nullable<System.Guid> AwayTeam { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
