//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hemsida.Data.DAL
{
    using Hemsida.Data.Repos;
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public UserInfo()
        {
        }
        public UserInfo(string id)
        {
            using(var db = new HemsidaEntities())
            {

            }
        }
        public UserInfo(string id, string nameOfUser)
        {
            using (var db = new HemsidaEntities())
            {
                userId = id;
                userName = nameOfUser;
            }

        }
        public UserInfo(Guid ide)
        {
            using (var db = new HemsidaEntities())
            {
                var repos = new AppUserRepos();
                var user = repos.GetUser(ide);
                id = user.id;
                userId = user.userId;
                firstName = user.firstName;
                lastName = user.lastName;
                age = user.age;
                userName = user.userName;
                Img = user.Img;

            }
        }
        public System.Guid id { get; set; }
        public string userId { get; set; }
        public string userName { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> age { get; set; }
        public byte[] Img { get; set; }
    }
}
